swagger: '2.0'
info:
  version: '1.0'
  title: "Documentazione API"

host: wave-edu-server.onrender.com:8080
basePath: /api
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /user:
    post:
      tags:
        - User
      summary: Create a new user
      parameters:
        - name: body
          in: body
          description: User object
          required: true
          schema:
            type: object
            properties:
              email:
                type: string             
              name:
                type: string
              UserType:
                type: string
      responses:
        "201":
          description: Created